//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'model_js_navigator.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelJsNavigator extends Model {
  //
  //
  //

  static const K_USER_AGENT = 'userAgent';

  static const CLASS = 'ModelJsNavigator';

  @override
  String get $class => CLASS;

  String? userAgent;

  //
  //
  //

  ModelJsNavigator.empty();

  //
  //
  //

  factory ModelJsNavigator({
    String? userAgent,
  }) {
    return ModelJsNavigator.b(
      userAgent: userAgent,
    );
  }

  //
  //
  //

  ModelJsNavigator.b({
    this.userAgent,
  }) {}

  //
  //
  //

  factory ModelJsNavigator.from(
    Model? other,
  ) {
    try {
      return fromOrNull(other)!;
    } catch (e) {
      assert(false, 'ModelJsNavigator.from: $e');
      rethrow;
    }
  }

  static ModelJsNavigator? fromOrNull(
    Model? other,
  ) {
    return fromJsonOrNull(other?.toJson())!;
  }

  //
  //
  //

  factory ModelJsNavigator.of(
    ModelJsNavigator other,
  ) {
    try {
      return ofOrNull(other)!;
    } catch (e) {
      assert(false, 'ModelJsNavigator.of: $e');
      rethrow;
    }
  }

  static ModelJsNavigator? ofOrNull(
    ModelJsNavigator? other,
  ) {
    return fromJsonOrNull(other?.toJson());
  }

  //
  //
  //

  factory ModelJsNavigator.fromJsonString(
    String source,
  ) {
    try {
      return fromJsonStringOrNull(source)!;
    } catch (e) {
      assert(false, 'ModelJsNavigator.fromJsonString: $e');
      rethrow;
    }
  }

  static ModelJsNavigator? fromJsonStringOrNull(
    String? source,
  ) {
    try {
      if (source!.isNotEmpty) {
        final decoded = jsonDecode(source);
        return ModelJsNavigator.fromJson(decoded);
      } else {
        return ModelJsNavigator.empty();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  factory ModelJsNavigator.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return fromJsonOrNull(otherData)!;
    } catch (e) {
      assert(false, 'ModelJsNavigator.fromJson: $e');
      rethrow;
    }
  }

  static ModelJsNavigator? fromJsonOrNull(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return ModelJsNavigator.empty()..$userAgent = otherData?[K_USER_AGENT];
    } catch (e) {
      return null;
    }
  }

  //
  //
  //

  factory ModelJsNavigator.fromUri(
    Uri? uri,
  ) {
    try {
      return fromUriOrNull(uri)!;
    } catch (e) {
      assert(false, 'ModelJsNavigator.fromUri: $e');
      rethrow;
    }
  }

  static ModelJsNavigator? fromUriOrNull(
    Uri? uri,
  ) {
    try {
      if (uri != null && uri.path == CLASS) {
        return ModelJsNavigator.fromJson(uri.queryParameters);
      } else {
        return ModelJsNavigator.empty();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final withNulls = <String, dynamic>{
        K_USER_AGENT: this.$userAgent,
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, 'ModelJsNavigator.toJson: $e');
      rethrow;
    }
  }

  //
  //
  //

  @override
  T empty<T extends Model>() {
    return ModelJsNavigator.b() as T;
  }

  //
  //
  //

  @override
  T copy<T extends Model>() {
    return (ModelJsNavigator.b()..updateWith(this)) as T;
  }

  //
  //
  //

  @override
  void updateWithJson(
    Map<String, dynamic>? otherData,
  ) {
    if (otherData != null && otherData.isNotEmpty) {
      final other = ModelJsNavigator.fromJson(otherData);
      if (other.userAgent != null) {
        this.userAgent = other.userAgent!;
      }
    }
  }

  //
  //
  //

  // userAgent.
  String? get userAgentField => this.userAgent;
  set userAgentField(String? v) => this.userAgent = v;
  @protected
  dynamic get $userAgent => this.userAgent?.toString().trim().nullIfEmpty;
  @protected
  set $userAgent(v) => this.userAgent = v?.toString().trim().nullIfEmpty;
}
