##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## 🇽🇾🇿 & Dev
##
## Licencing details are in the LICENSE file in the root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: xyz_device_info
description: This package allows you to get some basic device info and works with WebAssembly.
repository: https://github.com/robmllze/xyz_device_info
version: 0.9.0

## -----------------------------------------------------------------------------

environment:
  sdk: ">= 3.5.0 <4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  df_generate_dart_models_core: ^0.3.0

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^4.0.0
