##.title
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##
## 🇽🇾🇿 & Dev
##
## Licencing details are in the LICENSE file in the root directory.
##
## ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
##.title~

name: xyz_device_info
description: This package allows you to get some basic device info and works with WebAssembly.
repository: https://github.com/robmllze/xyz_device_info
version: 0.2.0

## -----------------------------------------------------------------------------

environment:
  sdk: ">= 3.3.1 < 4.0.0"

## -----------------------------------------------------------------------------

dependencies:
  xyz_gen_annotations: ^0.46.0

## -----------------------------------------------------------------------------

dev_dependencies:
  lints: ^4.0.0
