//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'model_global_position.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelGlobalPosition extends _ModelGlobalPosition {
  //
  //
  //

  static const K_ALTITUDE = 'altitude';
  static const K_LATITUDE = 'latitude';
  static const K_LONGITUDE = 'longitude';

  static const CLASS = 'ModelGlobalPosition';

  @override
  String get $class => CLASS;

  double? altitude;
  double? latitude;
  double? longitude;

  //
  //
  //

  ModelGlobalPosition.empty();

  //
  //
  //

  factory ModelGlobalPosition({
    double? altitude,
    double? latitude,
    double? longitude,
  }) {
    return ModelGlobalPosition.b(
      altitude: altitude,
      latitude: latitude,
      longitude: longitude,
    );
  }

  //
  //
  //

  ModelGlobalPosition.b({
    this.altitude,
    this.latitude,
    this.longitude,
  }) {}

  //
  //
  //

  factory ModelGlobalPosition.from(
    Model? other,
  ) {
    try {
      return fromOrNull(other)!;
    } catch (e) {
      assert(false, 'ModelGlobalPosition.from: $e');
      rethrow;
    }
  }

  static ModelGlobalPosition? fromOrNull(
    Model? other,
  ) {
    return fromJsonOrNull(other?.toJson())!;
  }

  //
  //
  //

  factory ModelGlobalPosition.of(
    ModelGlobalPosition other,
  ) {
    try {
      return ofOrNull(other)!;
    } catch (e) {
      assert(false, 'ModelGlobalPosition.of: $e');
      rethrow;
    }
  }

  static ModelGlobalPosition? ofOrNull(
    ModelGlobalPosition? other,
  ) {
    return fromJsonOrNull(other?.toJson());
  }

  //
  //
  //

  factory ModelGlobalPosition.fromJsonString(
    String source,
  ) {
    try {
      return fromJsonStringOrNull(source)!;
    } catch (e) {
      assert(false, 'ModelGlobalPosition.fromJsonString: $e');
      rethrow;
    }
  }

  static ModelGlobalPosition? fromJsonStringOrNull(
    String? source,
  ) {
    try {
      if (source!.isNotEmpty) {
        final decoded = jsonDecode(source);
        return ModelGlobalPosition.fromJson(decoded);
      } else {
        return ModelGlobalPosition.empty();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  factory ModelGlobalPosition.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return fromJsonOrNull(otherData)!;
    } catch (e) {
      assert(false, 'ModelGlobalPosition.fromJson: $e');
      rethrow;
    }
  }

  static ModelGlobalPosition? fromJsonOrNull(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return ModelGlobalPosition.empty()
        ..$altitude = otherData?[K_ALTITUDE]
        ..$latitude = otherData?[K_LATITUDE]
        ..$longitude = otherData?[K_LONGITUDE];
    } catch (e) {
      return null;
    }
  }

  //
  //
  //

  factory ModelGlobalPosition.fromUri(
    Uri? uri,
  ) {
    try {
      return fromUriOrNull(uri)!;
    } catch (e) {
      assert(false, 'ModelGlobalPosition.fromUri: $e');
      rethrow;
    }
  }

  static ModelGlobalPosition? fromUriOrNull(
    Uri? uri,
  ) {
    try {
      if (uri != null && uri.path == CLASS) {
        return ModelGlobalPosition.fromJson(uri.queryParameters);
      } else {
        return ModelGlobalPosition.empty();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final withNulls = <String, dynamic>{
        K_ALTITUDE: this.$altitude,
        K_LATITUDE: this.$latitude,
        K_LONGITUDE: this.$longitude,
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, 'ModelGlobalPosition.toJson: $e');
      rethrow;
    }
  }

  //
  //
  //

  @override
  T empty<T extends Model>() {
    return ModelGlobalPosition.b() as T;
  }

  //
  //
  //

  @override
  T copy<T extends Model>() {
    return (ModelGlobalPosition.b()..updateWith(this)) as T;
  }

  //
  //
  //

  @override
  void updateWithJson(
    Map<String, dynamic>? otherData,
  ) {
    if (otherData != null && otherData.isNotEmpty) {
      final other = ModelGlobalPosition.fromJson(otherData);
      if (other.altitude != null) {
        this.altitude = other.altitude!;
      }
      if (other.latitude != null) {
        this.latitude = other.latitude!;
      }
      if (other.longitude != null) {
        this.longitude = other.longitude!;
      }
    }
  }

  //
  //
  //

  // altitude.
  double? get altitudeField => this.altitude;
  set altitudeField(double? v) => this.altitude = v;
  @protected
  dynamic get $altitude => this.altitude;
  @protected
  set $altitude(v) => this.altitude = letDouble(v);

  // latitude.
  double? get latitudeField => this.latitude;
  set latitudeField(double? v) => this.latitude = v;
  @protected
  dynamic get $latitude => this.latitude;
  @protected
  set $latitude(v) => this.latitude = letDouble(v);

  // longitude.
  double? get longitudeField => this.longitude;
  set longitudeField(double? v) => this.longitude = v;
  @protected
  dynamic get $longitude => this.longitude;
  @protected
  set $longitude(v) => this.longitude = letDouble(v);
}
