//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: empty_constructor_bodies
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_this

part of 'basic_device_info.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class BasicDeviceInfo extends _BasicDeviceInfo {
  //
  //
  //

  static const K_OPERATING_SYSTEM = 'operating_system';
  static const K_USER_AGENT = 'user_agent';

  static const CLASS = 'BasicDeviceInfo';

  @override
  String get $class => CLASS;

  String? operatingSystem;
  String? userAgent;

  //
  //
  //

  BasicDeviceInfo.empty();

  //
  //
  //

  factory BasicDeviceInfo({
    String? operatingSystem,
    String? userAgent,
  }) {
    return BasicDeviceInfo.b(
      operatingSystem: operatingSystem,
      userAgent: userAgent,
    );
  }

  //
  //
  //

  BasicDeviceInfo.b({
    this.operatingSystem,
    this.userAgent,
  }) {}

  //
  //
  //

  factory BasicDeviceInfo.from(
    Model? other,
  ) {
    try {
      return fromOrNull(other)!;
    } catch (e) {
      assert(false, 'BasicDeviceInfo.from: $e');
      rethrow;
    }
  }

  static BasicDeviceInfo? fromOrNull(
    Model? other,
  ) {
    return fromJsonOrNull(other?.toJson())!;
  }

  //
  //
  //

  factory BasicDeviceInfo.of(
    BasicDeviceInfo other,
  ) {
    try {
      return ofOrNull(other)!;
    } catch (e) {
      assert(false, 'BasicDeviceInfo.of: $e');
      rethrow;
    }
  }

  static BasicDeviceInfo? ofOrNull(
    BasicDeviceInfo? other,
  ) {
    return fromJsonOrNull(other?.toJson());
  }

  //
  //
  //

  factory BasicDeviceInfo.fromJsonString(
    String source,
  ) {
    try {
      return fromJsonStringOrNull(source)!;
    } catch (e) {
      assert(false, 'BasicDeviceInfo.fromJsonString: $e');
      rethrow;
    }
  }

  static BasicDeviceInfo? fromJsonStringOrNull(
    String? source,
  ) {
    try {
      if (source!.isNotEmpty) {
        final decoded = jsonDecode(source);
        return BasicDeviceInfo.fromJson(decoded);
      } else {
        return BasicDeviceInfo.empty();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  factory BasicDeviceInfo.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return fromJsonOrNull(otherData)!;
    } catch (e) {
      assert(false, 'BasicDeviceInfo.fromJson: $e');
      rethrow;
    }
  }

  static BasicDeviceInfo? fromJsonOrNull(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return BasicDeviceInfo.empty()
        ..$operatingSystem = otherData?[K_OPERATING_SYSTEM]
        ..$userAgent = otherData?[K_USER_AGENT];
    } catch (e) {
      return null;
    }
  }

  //
  //
  //

  factory BasicDeviceInfo.fromUri(
    Uri? uri,
  ) {
    try {
      return fromUriOrNull(uri)!;
    } catch (e) {
      assert(false, 'BasicDeviceInfo.fromUri: $e');
      rethrow;
    }
  }

  static BasicDeviceInfo? fromUriOrNull(
    Uri? uri,
  ) {
    try {
      if (uri != null && uri.path == CLASS) {
        return BasicDeviceInfo.fromJson(uri.queryParameters);
      } else {
        return BasicDeviceInfo.empty();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final withNulls = <String, dynamic>{
        K_OPERATING_SYSTEM: this.$operatingSystem,
        K_USER_AGENT: this.$userAgent,
      }.mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, 'BasicDeviceInfo.toJson: $e');
      rethrow;
    }
  }

  //
  //
  //

  @override
  T empty<T extends Model>() {
    return BasicDeviceInfo.b() as T;
  }

  //
  //
  //

  @override
  T copy<T extends Model>() {
    return (BasicDeviceInfo.b()..updateWith(this)) as T;
  }

  //
  //
  //

  @override
  void updateWithJson(
    Map<String, dynamic>? otherData,
  ) {
    if (otherData != null && otherData.isNotEmpty) {
      final other = BasicDeviceInfo.fromJson(otherData);
      if (other.operatingSystem != null) {
        this.operatingSystem = other.operatingSystem!;
      }
      if (other.userAgent != null) {
        this.userAgent = other.userAgent!;
      }
    }
  }

  //
  //
  //

  // operatingSystem.
  String? get operatingSystemField => this.operatingSystem;
  set operatingSystemField(String? v) => this.operatingSystem = v;
  @protected
  dynamic get $operatingSystem =>
      this.operatingSystem?.toString().trim().nullIfEmpty;
  @protected
  set $operatingSystem(v) =>
      this.operatingSystem = v?.toString().trim().nullIfEmpty;

  // userAgent.
  String? get userAgentField => this.userAgent;
  set userAgentField(String? v) => this.userAgent = v;
  @protected
  dynamic get $userAgent => this.userAgent?.toString().trim().nullIfEmpty;
  @protected
  set $userAgent(v) => this.userAgent = v?.toString().trim().nullIfEmpty;
}
