//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY 🇽🇾🇿 GEN - DO NOT MODIFY BY HAND
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

// ignore_for_file: annotate_overrides
// ignore_for_file: invalid_null_aware_operator
// ignore_for_file: overridden_fields
// ignore_for_file: unnecessary_non_null_assertion
// ignore_for_file: unnecessary_null_comparison
// ignore_for_file: unnecessary_question_mark
// ignore_for_file: unnecessary_this

part of 'model_basic_device_info.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

class ModelBasicDeviceInfo extends _ModelBasicDeviceInfo {
  //
  //
  //

  static const CLASS_NAME = 'ModelBasicDeviceInfo';

  @override
  String get $className => CLASS_NAME;

  final String? operatingSystem;
  final String? userAgent;
  final bool? isInstalled;

  //
  //
  //

  const ModelBasicDeviceInfo({
    this.operatingSystem,
    this.userAgent,
    this.isInstalled,
  });

  const ModelBasicDeviceInfo.c2({
    this.operatingSystem,
    this.userAgent,
    this.isInstalled,
  });

  factory ModelBasicDeviceInfo.c3({
    String? operatingSystem,
    String? userAgent,
    bool? isInstalled,
  }) {
    return ModelBasicDeviceInfo(
      operatingSystem: operatingSystem,
      userAgent: userAgent,
      isInstalled: isInstalled,
    );
  }

  factory ModelBasicDeviceInfo.from(
    BaseModel? other,
  ) {
    try {
      return fromOrNull(other)!;
    } catch (e) {
      assert(false, 'ModelBasicDeviceInfo.from: $e');
      rethrow;
    }
  }

  static ModelBasicDeviceInfo? fromOrNull(
    BaseModel? other,
  ) {
    return fromJsonOrNull(other?.toJson())!;
  }

  factory ModelBasicDeviceInfo.of(
    ModelBasicDeviceInfo other,
  ) {
    try {
      return ofOrNull(other)!;
    } catch (e) {
      assert(false, 'ModelBasicDeviceInfo.of: $e');
      rethrow;
    }
  }

  static ModelBasicDeviceInfo? ofOrNull(
    ModelBasicDeviceInfo? other,
  ) {
    return fromJsonOrNull(other?.toJson());
  }

  factory ModelBasicDeviceInfo.fromJsonString(
    String source,
  ) {
    try {
      return fromJsonStringOrNull(source)!;
    } catch (e) {
      assert(false, 'ModelBasicDeviceInfo.fromJsonString: $e');
      rethrow;
    }
  }

  static ModelBasicDeviceInfo? fromJsonStringOrNull(
    String? source,
  ) {
    try {
      if (source!.isNotEmpty) {
        final decoded = jsonDecode(source);
        return ModelBasicDeviceInfo.fromJson(decoded);
      } else {
        return const ModelBasicDeviceInfo.c2();
      }
    } catch (_) {
      return null;
    }
  }

  factory ModelBasicDeviceInfo.fromJson(
    Map<String, dynamic>? otherData,
  ) {
    try {
      return fromJsonOrNull(otherData)!;
    } catch (e) {
      assert(false, 'ModelBasicDeviceInfo.fromJson: $e');
      rethrow;
    }
  }

  static ModelBasicDeviceInfo? fromJsonOrNull(
    Map<String, dynamic>? otherData,
  ) {
    try {
      final operatingSystem0 = otherData?['operatingSystem'];
      final operatingSystem = operatingSystem0?.toString().trim().nullIfEmpty;
      final userAgent0 = otherData?['userAgent'];
      final userAgent = userAgent0?.toString().trim().nullIfEmpty;
      final isInstalled0 = otherData?['isInstalled'];
      final isInstalled = letBool(isInstalled0);
      return ModelBasicDeviceInfo(
        operatingSystem: operatingSystem,
        userAgent: userAgent,
        isInstalled: isInstalled,
      );
    } catch (e) {
      return null;
    }
  }

  factory ModelBasicDeviceInfo.fromUri(
    Uri? uri,
  ) {
    try {
      return fromUriOrNull(uri)!;
    } catch (e) {
      assert(false, 'ModelBasicDeviceInfo.fromUri: $e');
      rethrow;
    }
  }

  static ModelBasicDeviceInfo? fromUriOrNull(
    Uri? uri,
  ) {
    try {
      if (uri != null && uri.path == CLASS_NAME) {
        return ModelBasicDeviceInfo.fromJson(uri.queryParameters);
      } else {
        return const ModelBasicDeviceInfo.c2();
      }
    } catch (_) {
      return null;
    }
  }

  //
  //
  //

  @override
  Map<String, dynamic> toJson({
    dynamic defaultValue,
    bool includeNulls = false,
  }) {
    try {
      final operatingSystem0 = this.operatingSystem?.trim().nullIfEmpty;
      final userAgent0 = this.userAgent?.trim().nullIfEmpty;
      final isInstalled0 = this.isInstalled;
      final withNulls = mergeMapsDeep([
        {
          'operatingSystem': operatingSystem0,
        },
        {
          'userAgent': userAgent0,
        },
        {
          'isInstalled': isInstalled0,
        },
      ]).mapWithDefault(defaultValue);
      return includeNulls ? withNulls : withNulls.nonNulls;
    } catch (e) {
      assert(false, 'ModelBasicDeviceInfo.toJson: $e');
      rethrow;
    }
  }

  //
  //
  //

  @override
  ModelBasicDeviceInfo copyWith(BaseModel? other) {
    final a = this.toJson();
    final b = other?.toJson();
    final c = {...a, ...?b};
    return ModelBasicDeviceInfo.fromJson(c);
  }

  //
  //
  //

  // operatingSystem.
  String? get operatingSystemField => this.operatingSystem;

  // userAgent.
  String? get userAgentField => this.userAgent;

  // isInstalled.
  bool? get isInstalledField => this.isInstalled;
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

final class ModelBasicDeviceInfoFieldNames {
  //
  //
  //

  static const operatingSystem = 'operatingSystem';
  static const userAgent = 'userAgent';
  static const isInstalled = 'isInstalled';

  //
  //
  //

  const ModelBasicDeviceInfoFieldNames._();
}
