//.title
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//
// GENERATED BY XYZ_GENIE
// See: https://github.com/robmllze/xyz_gen
//
// ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓
//.title~

import '/_common.dart';

part '_model_basic_device_info.g.dart';

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

typedef BasicDeviceInfo = ModelBasicDeviceInfo;

@GenerateModel(
  shouldInherit: true,
  fields: {
    ('operating_system?', String),
    ('user_agent?', String),
    ('is_installed?', bool),
  },
)
abstract class _ModelBasicDeviceInfo extends Model {
  const _ModelBasicDeviceInfo();
}

// ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░

extension ModelBasicDeviceInfoExtension on ModelBasicDeviceInfo {
  bool userAgentIsSafari() {
    final source = this.userAgent?.toLowerCase() ?? '';
    return source.contains('safari');
  }

  bool userAgentIsChrome() {
    final source = this.userAgent?.toLowerCase() ?? '';
    return source.contains('chrome');
  }

  bool userAgentIsMacOS() {
    final source = this.userAgent?.toLowerCase() ?? '';
    return source.contains('mac os') || source.contains('macos');
  }

  bool userAgentIsWindows() {
    final source = this.userAgent?.toLowerCase() ?? '';
    return source.contains('windows');
  }

  bool userAgentIsAndroid() {
    final source = this.userAgent?.toLowerCase() ?? '';
    return source.contains('android');
  }
}
